---
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - Gemfile
  - Rakefile
  - 'test/**/*'
  - 'examples/plugins/train-*/test/**/*'
  - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: true
Layout/MultilineAssignmentLayout:
  Enabled: true
Layout/ParameterAlignment:
  Enabled: true
Style/Encoding:
  Enabled: false
Style/HashSyntax:
  Enabled: true
Layout/LineLength:
  Enabled: true
  AutoCorrect: true
  Max: 8192
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Metrics/BlockLength:
  Enabled: true
  Max: 8192
Metrics/MethodLength:
  Enabled: true
Style/NumericLiterals:
  MinDigits: 10
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 33
Metrics/ModuleLength:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Layout/HashAlignment:
  Enabled: true
Naming/PredicateName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: true
Style/ConditionalAssignment:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/NegatedIf:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/BlockDelimiters:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent
  IndentationWidth: 2
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument
  IndentationWidth: 2
Layout/ArrayAlignment:
  Enabled: true
Layout/AssignmentIndentation:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal
Layout/IndentationWidth:
  Enabled: true
  Width: 2
Layout/InitialIndentation:
  Enabled: true
Layout/LeadingCommentSpace:
  Enabled: true
