---
inherit_from: .rubocop_todo.yml

require: rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
  - Gemfile
  - Rakefile
  - 'vendor/**/*'
Gemspec/DateAssignment: # (new in 1.10)
  Enabled: true
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/StringChars: # (new in 1.12)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
Minitest/AssertInDelta: # (new in 0.10)
  Enabled: true
Minitest/AssertionInLifecycleHook: # (new in 0.10)
  Enabled: true
Minitest/AssertKindOf: # (new in 0.10)
  Enabled: true
Minitest/AssertOutput: # (new in 0.10)
  Enabled: false
Minitest/AssertPathExists: # (new in 0.10)
  Enabled: true
Minitest/AssertSilent: # (new in 0.10)
  Enabled: true
Minitest/AssertWithExpectedArgument: # (new in 0.11)
  Enabled: true
Minitest/LiteralAsActualArgument: # (new in 0.10)
  Enabled: true
Minitest/RefuteInDelta: # (new in 0.10)
  Enabled: true
Minitest/RefuteKindOf: # (new in 0.10)
  Enabled: true
Minitest/RefutePathExists: # (new in 0.10)
  Enabled: true
Minitest/TestMethodName: # (new in 0.10)
  Enabled: true
Minitest/UnspecifiedException: # (new in 0.10)
  Enabled: true
Minitest/MultipleAssertions:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: true
Layout/MultilineAssignmentLayout:
  Enabled: true
Layout/ParameterAlignment:
  Enabled: true
Style/Encoding:
  Enabled: false
Style/HashSyntax:
  Enabled: true
Layout/LineLength:
  Enabled: true
  AutoCorrect: true
  Max: 8192
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
Metrics/BlockLength:
  Enabled: true
  Max: 8192
Style/NumericLiterals:
  MinDigits: 10
Metrics/ModuleLength:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Layout/HashAlignment:
  Enabled: true
Naming/PredicateName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: true
Style/ConditionalAssignment:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/NegatedIf:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/BlockDelimiters:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent
  IndentationWidth: 2
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument
  IndentationWidth: 2
Layout/ArrayAlignment:
  Enabled: true
Layout/AssignmentIndentation:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal
Layout/IndentationWidth:
  Enabled: true
  Width: 2
Layout/InitialIndentation:
  Enabled: true
Layout/LeadingCommentSpace:
  Enabled: true
