os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - RUBY_VERSION: 26
    - RUBY_VERSION: 25
    - RUBY_VERSION: 24

branches:
  only:
    - master

cache:
  - vendor/bundle -> appveyor.yml

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - ruby -r rubygems -e "p Gem.path"

build_script:
  - bundle install --path=vendor/bundle --without integration tools maintenance deploy

test_script:
  - bundle exec rake test:windows
