source 'https://rubygems.org'

gem 'colorize'
gem 'docsplit', :git => 'https://github.com/documentcloud/docsplit.git'
gem 'inspec', '>= 2.2.61'
gem 'nokogiri'
gem 'nokogiri-happymapper', require: 'happymapper'
gem 'OptionParser'
gem 'pdftotext'
gem 'pry'
gem 'roo'
gem 'rspec'
gem 'thor'
gem 'word_wrap'
