module Utils
  class MappingValidator
    def self.validate(mapping)
      require 'pry'; binding.pry
      return mapping unless mapping.include?('control.tags')

      return mapping unless mapping['control.tags'].include?('nist')

      raise "Mapping file should not contain an entry for 'control.tags.nist'.
            NIST tags will be autogenerated via 'control.tags.cci'."
    end
  end
end
