#!/usr/bin/env ruby
# encoding: utf-8
# author: Rony Xavier rx294@nyu.edu

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require_relative '../lib/csv2inspec'
require_relative '../lib/csv2inspec/cli'
InspecTo::MyCLI.start(ARGV)
