#!/usr/bin/env ruby
# encoding: utf-8
# author: Aaron Lippold
# author: Rony Xavier rx294@nyu.edu

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require_relative '../lib/inspec2xccdf/inspec2xccdf'
require_relative '../lib/inspec2xccdf/cli'
InspecTo::MyCLI.start(ARGV)
