#!/usr/bin/env -S ruby -EUTF-8

# Trap ^C
Signal.trap('INT') do
  puts "\nCtrl-C detected. Exiting..."
  sleep 1
  exit
end

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'inspec_tools'
require 'inspec_tools/cli'

InspecTools::CLI.start(ARGV)
