#!/usr/bin/env -S ruby -E UTF-8

# Trap ^C
Signal.trap('INT') {
  puts "\nCtrl-C detected. Exiting..."
  sleep 1
  exit
}

$LOAD_PATH.unshift(File.expand_path('../lib', __dir__))
require 'inspec_tools'
require 'inspec_tools/cli'

InspecTools::CLI.start(ARGV)
