#!/usr/bin/env ruby
# encoding: utf-8
# author: Aaron Lippold (alippold@mitre.org)
# author: Rony Xavier (rxavier@mitre.org)

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require_relative '../lib/inspec2ckl'
require_relative '../lib/inspec2ckl/cli'
InspecTo::MyCLI.start(ARGV)
