#!/usr/bin/env ruby
# encoding: utf-8
# author: Matthew Dromazos

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require_relative '../lib/xccdf2inspec'
require_relative '../lib/xccdf2inspec/cli'

InspecTo::MyCLI.start(ARGV)
