name: Release Gem

on:
  release:
    types: [published]

jobs:
  release_gem:
    name: Release to gem hosts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout inspec_tools
        uses: actions/checkout@v2
      - name: Publish to Rubygems
        uses: cadwallion/publish-rubygems-action@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        env:
          RELEASE_COMMAND: rake publish
      - name: Publish to GitHub
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: mitre
