name: Push to Master Actions
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Push to Master Actions
    runs-on: ubuntu-latest
    steps:
       - name: Setup ruby
         uses: actions/setup-ruby@v1
       - name: Checkout inspec_tools
         uses: actions/checkout@v2
       - name: Increment version and push tag dry run for Gem Version
         uses: anothrNick/github-tag-action@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: patch
           WITH_V: false
           DRY_RUN: true
         id: tag
       - name: Increment Gem Version
         run: printf "module InspecTools\n  VERSION = '${{ steps.tag.outputs.new_tag }}'.freeze\nend\n" > lib/inspec_tools/version.rb
       - name: Git Auto Commit
         uses: stefanzweifel/git-auto-commit-action@v4.1.0
         with:
           commit_message: 'Update version.rb'
           branch: 'master'
       - name: Increment version and push tag
         uses: anothrNick/github-tag-action@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: patch
           WITH_V: true
           DRY_RUN: false
       - name: Install and run github_changelog_generator
         run: |
           gem install github_changelog_generator --no-document
           export CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
           github_changelog_generator -u mitre -p inspec_tools
       - name: Git Auto Commit
         uses: stefanzweifel/git-auto-commit-action@v4.1.0
         with:
           commit_message: 'Update CHANGELOG.md'
           branch: 'master'
