name: Test Docker

on:
  pull_request:
    branches: [ master ]

jobs:
  release-gem-hosts:
    name: Release to gem hosts
    runs-on: ubuntu-latest
    steps:
      - name: Setup ruby
        uses: actions/setup-ruby@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Setup credentials and versioning
        run: |
          gem install git-lite-version-bump keycutter roo
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          printf -- ":github: Bearer ${GPR_API_KEY}\n" >> $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          GPR_API_KEY: ${{secrets.GITHUB_TOKEN}}
      - name: Build gem
        run: rake build_release
        env:
          NIST_MAPPING_CIS_CONTROLS: NIST_Map_02052020_CIS_Controls_Version_7.1_Implementation_Groups_1.2.xlsx
          NIST_MAPPING_CIS_CRITICAL_CONTROLS: NIST_Map_09212017B_CSC-CIS_Critical_Security_Controls_VER_6.1_Excel_9.1.2016.xlsx
      - name: Get gem version
        run: echo "::set-env name=VERSION::$(ls *.gem | grep -Po '(\d+.)+\d+')"
      - name: Log in to docker
        run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - name: Build container
        run: docker build . --tag mitre/inspec_tools:$VERSION
